### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#264]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

master

### Node.js version

12.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

circleci

### Description

CircleCI fails to buld with

```
TypeError: Cannot read property '1' of null
    at /home/circleci/fastify-website/src/scripts/processReleases.js:233:23
    at Array.map (<anonymous>)
    at extractPlugins (/home/circleci/fastify-website/src/scripts/processReleases.js:231:31)
    at extractEcosystemFromFile (/home/circleci/fastify-website/src/scripts/processReleases.js:256:23)
    at async createEcosystemDataFile (/home/circleci/fastify-website/src/scripts/processReleases.js:269:21)
    at async main (/home/circleci/fastify-website/src/scripts/processReleases.js:26:3)
```

### Steps to Reproduce

Unsure, https://app.circleci.com/jobs/github/fastify/website/2634?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by mcollina** [comment]
cc @lmammino

**Comment by lmammino** [comment]
Checking 👀
