### ISSUE TITLE
Website build broken

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#31]
The website build is currently broken with the following error:

```
> src/scripts/processReleases.js build-temp/releases src/website

/home/circleci/fastify-website/src/scripts/processReleases.js:232
      const name = match[1]
                        ^

TypeError: Cannot read property '1' of null
    at mergedLines.map (/home/circleci/fastify-website/src/scripts/processReleases.js:232:25)
    at Array.map (<anonymous>)
    at readFile (/home/circleci/fastify-website/src/scripts/processReleases.js:230:33)
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
```

The same error happens also local.

Currently investigating on this

**Comment by lmammino** [comment]
It turns out this is happening on plugin parsing. A patch is coming soon
