### ISSUE TITLE
Rate limit to Github API

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#63]
```
node src/scripts/downloadReleases.js fastify/fastify build-temp/releases v0.11.0

downloading releases into /home/circleci/fastify-website/build-temp/releases
{ StatusCodeError: 403 - {"message":"API rate limit exceeded for 52.90.181.163. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
    at new StatusCodeError (/home/circleci/fastify-website/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/circleci/fastify-website/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/circleci/fastify-website/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/circleci/fastify-website/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/circleci/fastify-website/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/circleci/fastify-website/node_modules/request/request.js:1091:12)
  name: 'StatusCodeError',
```

**Comment by lmammino** [comment]
woops! That's an interesting one! I guess an easy win would be to do authenticated requests. Additionally I can think of some caching mechanism (since circleCI supports caching as well).

I'll have a look into this!
